services:
  reverse-proxy:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--providers.file.directory=/config"

      # Expose HTTP and HTTPS entrypoints, Apply 301 redirection to HTTPS
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # Configure log files to the mounted dir and log levels
      - "--accesslog"
      - "--accesslog.filepath=/logs/access.log"
      - "--log"
      - "--log.filepath=/logs/traefik.log"
      # - "--log.level=DEBUG"
    ports:
      # The HTTP(s) port
      - 80:80
      - 443:443
      # Traefik Web UI (enabled by --api.insecure=true) // Firewall blocks port 8080 so this can be exposed
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Logs outside of container
      - ~/data/logs:/logs
      # Traefik Dynamic configs
      - ./traefik:/config
    secrets:
      # Expose SSL certificates as secrets
      - cert
      - key
    networks:
      proxy: {}

networks:
  proxy:
    driver: bridge
    attachable: true
    name: proxy

secrets:
  cert:
    file: /etc/cloudflare/cert.pem
  key:
    file: /etc/cloudflare/key.pem
