services:
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ~/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      db.mysql: {}

networks:
  db.mysql:
    driver: bridge
    attachable: true
    name: db.mysql
